<?php
function boskoa_register_strings() {

    $strings = [
        'Boskoa Travel',
        'Costa Rica',
        'Change language',
        'Your cart',
        'Your cart is empty',
        'Complete Your Booking',
        'Name',
        'Your full name',
        'Email',
        'Phone (optional)',
        'Message',
        'I would like to book these activities...',
        'Send Booking Request',
        'Oops... this page got lost in the system.',
        'Back to home',
        'The Team',
        'Who We Are',
        'Discover our passion for Costa Rica and sustainable tourism',
        'We are here',
        'Loading activities...',
        'No activities available.',
        'We are working on new activities. Please come back soon.',
        'To learn more about our products and services, write to us and we will gladly assist you.',
        'Matters',
        'Send now',
        'Contact Us',
        'All Rights Reserved',
        'Our Activities',
        'See all activities',
        'Our packages',
        'See all tours',
        '+2 MILLIONS',
        'Many people visit this natural paradise',
        'What our customer say!!',
        'Family Friendly',
        'Description',
        'Enjoy your vacation with our package:',
        'Included Activities',
        'You save',
        'Persons',
        'Package price',
        'Book Now',
        'View other packages',
        'Activities Included in This Package',
        'INCLUDED',
        'ADDITIONAL INFORMATION',
        'Book Your Package',
        'Phone (optional)',
        'I would like to book this package...',
        'I would like to book the package "',
        '" for $',
        'Loading packages...',
        'No packages available.',
        'We are working on new tour packages. Please come back soon.',
        'Add First Package',
        'Previous page',
        'Go to page',
        'Next page',
        'Enjoy your vacation with our activities:',
        'Host languages',
        'MEETING POINT',
        'Open in Google Maps',
        'ITINERARY',
        'Book Your Tour',
        'I would like to book the following activities:',
        'Please contact me with more information.',
        'Family',
        'Message sent!',
        'Thank you for contacting us. We will get back to you soon.',
        'Error sending.',
        'Please check the information and try again.',
        'Book now package-card',
        'One Way',
        'Round Trip',
        'One Way / Round Trip',
        'Contact for pricing',
        'Booking confirmation - Boskoa Travels',
        'We have received your booking request and will get back to you shortly.',
        'Your order summary:',
        'Estimated total',
        'Best regards,',
        'The Boskoa Travels team',
        'Thank you for contacting us!',
        'Summary of your message:',
        'Subject',
        'Price per person',
        'Package',
        'Activity',
        'Hello',
        'Clear cart',
        'We have received your message and will get back to you shortly.'
        
    ];

    foreach ($strings as $string) {
        pll_register_string(
            sanitize_title($string),
            $string,
            'Boskoa Theme'
        );
    }

}

add_action('init', 'boskoa_register_strings');