<?php
function boskoa_register_strings() {

    $strings = [
        'SEE PACKS →',
        '+2 MILLIONS',
        'Many people visit this natural paradise',
        'Contact us >>',
        'What our customer say!!',
        'See all activities',
        'Our Activities',
        'Our packets',
        'See all tours',
        'Costa Rica',
        'To learn more about our products and services, write to us and we will gladly assist you.',
        'Name',
        'Email',
        'Matters',
        'Message',
        'Send now',
        'All Rights Reserved',
        'No activities available.',
        'We are working on new activities. Please come back soon.',
        'Loading packages...',
        'No packages available.',
        'We are working on new tour packages. Please come back soon.',
        'Add First Package',
        'Previous page',
        'Go to page',
        'Next page',
        'Enjoy your vacation with our tour:',
        'Book Now',
        'View other activities',
        'DESCRIPTION',
        'ADDITIONAL INFORMATION',
        'Host languages',
        'MEETING POINT',
        'Open in Google Maps',
        'ITINERARY',
        'The Team',
        'Message sent!',
        'Thank you for contacting us. We will get back to you soon.',
        'Error sending.',
        'Please check the information and try again.',
        'Book now package-card',
        'Contact Us',
        'Loading activities...',
        'Enjoy your vacation with our activities:',
        'BookNow-sidebar',
        'Clear cart',
        'Your cart is empty.',
        'Order Summary',
        'Total',
        'Sending...',
        '✓ Added!',
        'Add to cart',
        'Thank you! Your booking request has been sent successfully.',
        'There was an error sending your request. Please try again.',
        'I would like to book the following activities:',
        'Please contact me with more information.',
        'Boskoa Travel',
        'Change language',
        'Tu carrito',
        'Tu carrito está vacío.',
        'Complete Your Booking',
        'Your full name',
        'Phone (optional)',
        'I would like to book these activities...',
        'Send Booking Request',
    ];

    foreach ($strings as $string) {
        pll_register_string(
            sanitize_title($string),
            $string,
            'Boskoa Theme'
        );
    }

}

add_action('init', 'boskoa_register_strings');